name: Build test
on: [push]
jobs:
    build-test:
        name: Build Next.js app
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup Pnpm
              uses: pnpm/action-setup@v6

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build app
              run: pnpm run build
